%% 基于 WFBG 的级联光栅微波光子滤波器时频分析仿真
clc; clear; close all;
%% 图 1：12 抽头 MPF 的时域与频域响应
a_k = [1,1,1,1,1,1,1,1,1,1,1,1];
N = length(a_k);
L = [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1];
[f, H_omega, t, h] = MPF_IFFT(N, a_k, L);
figure;
subplot(2,1,1);
plot(t, abs(h), 'b', 'LineWidth', 1.5);
xlim([0 0.013]);
xlabel('Time (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
ylabel('Magnitude (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
title(sprintf('Time Response of %d-Tap MPF', N));
grid on; set(gca, 'box', 'on');
set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
subplot(2,1,2);
plot(f.*1e-9, abs(H_omega), 'b', 'LineWidth', 1.5);
xlim([min(f.*1e-9) max(f.*1e-9)]);
xlabel('Frequency (GHz)', 'FontName', 'Times New Roman', 'FontSize', 10);
ylabel('Magnitude (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
title(sprintf('Frequency Response of %d-Tap MPF', N));
grid on; set(gca, 'box', 'on');
set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
set(gcf, 'Renderer', 'OpenGL');
print(gcf, 'fig1.jpg', '-djpeg', '-r600');
%% 图 2：仅一个 WFBG 幅度不为 0
figure;
a_k = 1; N = 1; L = 0.6;
subplot(2,1,1);
[~, ~, t, h] = MPF_IFFT(N, a_k, L);
plot(t, abs(h), 'b', 'LineWidth', 1.5);
xlim([0 0.013]);
xlabel('Time (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
ylabel('Magnitude (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
title(sprintf('Time Response of %d-Grating Structure', N));
grid on; set(gca, 'box', 'on');
set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
subplot(2,1,2);
[f, H_omega, ~, ~] = MPF_IFFT(N, a_k, L);
plot(f.*1e-9, abs(H_omega), 'b', 'LineWidth', 1.5);
xlim([min(f.*1e-9) max(f.*1e-9)]);
ylim([0 2]);
xlabel('Frequency (GHz)', 'FontName', 'Times New Roman', 'FontSize', 10);
ylabel('Magnitude (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
title(sprintf('Frequency Response of %d-Grating Structure', N));
grid on; set(gca, 'box', 'on');
set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
set(gcf, 'Renderer', 'OpenGL');
print(gcf, 'fig2.jpg', '-djpeg', '-r600');
