 %% 基于光注入半导体激光器的微波信号产生仿真
 clc; clear; close all;
 % 四个振荡态：稳态锁定、单周期、倍周期、混沌
 % 失谐频率 fi：5.5 GHz，光注入强度 xi 变化
 %% 图 1：稳态锁定态
 y0_ = [0.222; 1.068; -0.105];
 [f1, P1, t, y2, f3, P3, n_, y4] = F(5.5e9, 0.29, y0_);
 figure;
 subplot(221);
 plot(f1, P1, 'b', 'LineWidth', 1.5);
 xlim([-40e9 40e9]); ylim([30 36]);
 xlabel('Frequency (Hz)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('Optical Power (dB)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Optical Spectrum');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(222);
 plot(t, y2, 'b', 'LineWidth', 1.5);
 xlim([0 10e-10]); ylim([0 4]);
 xlabel('Time (s)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('Intensity, |a|^2 (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Time Series');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(223);
 plot(f3, P3, 'b', 'LineWidth', 1.5);
 xlim([0 40e9]); ylim([30 36]);
 xlabel('Frequency (Hz)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('RF Power (dB)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('RF Spectrum');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(224);
 plot(n_, y4, 'b', 'LineWidth', 1.5);
 xlim([-0.3 0.3]); ylim([0 2]);
 xlabel('n~ (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('|a| (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Phase Portrait');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 set(gcf, 'Renderer', 'OpenGL');
 print(gcf, 'fig1.jpg', '-djpeg', '-r600');
 %% 图 2：单周期振荡态
 y0_ = [0.25; 0.05; 0];
 [f1, P1, t, y2, f3, P3, n_, y4] = F(5.5e9, 0.115, y0_);
 figure;
 subplot(221);
 plot(f1, P1, 'b', 'LineWidth', 1.5);
 xlim([-40e9 40e9]); ylim([30 36]);
 xlabel('Frequency (Hz)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('Optical Power (dB)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Optical Spectrum');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(222);
 plot(t, y2, 'b', 'LineWidth', 1.5);
 xlim([0 10e-10]); ylim([0 4]);
 xlabel('Time (s)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('Intensity, |a|^2 (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Time Series');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(223);
 plot(f3, P3, 'b', 'LineWidth', 1.5);
 xlim([0 40e9]); ylim([30 36]);
 xlabel('Frequency (Hz)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('RF Power (dB)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('RF Spectrum');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(224);
 plot(n_, y4, 'b', 'LineWidth', 1.5);
 xlim([-0.3 0.3]); ylim([0 2]);
 xlabel('n~ (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('|a| (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Phase Portrait');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 set(gcf, 'Renderer', 'OpenGL');
 print(gcf, 'fig2.jpg', '-djpeg', '-r600');
 %% 图 3：倍周期振荡态
 y0_ = [0.222; 1.066; -0.115];
 [f1, P1, t, y2, f3, P3, n_, y4] = F(5.5e9, 0.0595, y0_);
 figure;
 subplot(221);
 plot(f1, P1, 'b', 'LineWidth', 1.5);
 xlim([-40e9 40e9]); ylim([30 36]);
 xlabel('Frequency (Hz)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('Optical Power (dB)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Optical Spectrum');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(222);
 plot(t, y2, 'b', 'LineWidth', 1.5);
 xlim([0 10e-10]); ylim([0 4]);
 xlabel('Time (s)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('Intensity, |a|^2 (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Time Series');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(223);
 plot(f3, P3, 'b', 'LineWidth', 1.5);
 xlim([0 40e9]); ylim([30 36]);
 xlabel('Frequency (Hz)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('RF Power (dB)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('RF Spectrum');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(224);
 plot(n_, y4, 'b', 'LineWidth', 1.5);
 xlim([-0.3 0.3]); ylim([0 2]);
 xlabel('n~ (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('|a| (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Phase Portrait');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 set(gcf, 'Renderer', 'OpenGL');
 print(gcf, 'fig3.jpg', '-djpeg', '-r600');
 %% 图 4：混沌振荡态
 y0_ = [0.25; 0.05; 0];
 [f1, P1, t, y2, f3, P3, n_, y4] = F(5.5e9, 0.039, y0_);
 figure;
 subplot(221);
 plot(f1, P1, 'b', 'LineWidth', 1.5);
 xlim([-40e9 40e9]); ylim([30 36]);
 xlabel('Frequency (Hz)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('Optical Power (dB)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Optical Spectrum');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(222);
 plot(t, y2, 'b', 'LineWidth', 1.5);
 xlim([0 10e-10]); ylim([0 4]);
 xlabel('Time (s)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('Intensity, |a|^2 (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Time Series');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(223);
 plot(f3, P3, 'b', 'LineWidth', 1.5);
 xlim([0 40e9]); ylim([30 36]);
 xlabel('Frequency (Hz)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('RF Power (dB)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('RF Spectrum');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 subplot(224);
 plot(n_, y4, 'b', 'LineWidth', 1.5);
 xlim([-0.3 0.3]); ylim([0 2]);
 xlabel('n~ (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 ylabel('|a| (a.u.)', 'FontName', 'Times New Roman', 'FontSize', 10);
 title('Phase Portrait');
 grid on; set(gca, 'box', 'on');
 set(gca, 'FontName', 'Times New Roman', 'FontSize', 10); set(gca, 'LineWidth', 1);
 set(gcf, 'Renderer', 'OpenGL');
 print(gcf, 'fig4.jpg', '-djpeg', '-r600');
